# Generated by Django 5.2.7 on 2025-10-27 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WatchlistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin_id', models.CharField(db_index=True, max_length=100)),
                ('coin_name', models.CharField(max_length=200)),
                ('coin_symbol', models.CharField(max_length=20)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('last_price', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-added_at'],
                'unique_together': {('coin_id',)},
            },
        ),
    ]
