# Generated by Django 5.2.7 on 2025-10-31 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='watchlistitem',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='watchlistitem',
            name='coin_id',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
    ]
