# Generated by Django 5.2.8 on 2025-11-30 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_api', '0002_alter_watchlistitem_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlistitem',
            name='alert_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='watchlistitem',
            name='alert_price_threshold',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='watchlistitem',
            name='circulating_supply',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=30, null=True),
        ),
        migrations.AddField(
            model_name='watchlistitem',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='watchlistitem',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='watchlistitem',
            name='is_favorite',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='watchlistitem',
            name='market_cap',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True),
        ),
        migrations.AddField(
            model_name='watchlistitem',
            name='max_supply',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=30, null=True),
        ),
        migrations.AddField(
            model_name='watchlistitem',
            name='price_change_24h',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='watchlistitem',
            name='total_supply',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=30, null=True),
        ),
        migrations.AddField(
            model_name='watchlistitem',
            name='volume_24h',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True),
        ),
        migrations.AddField(
            model_name='watchlistitem',
            name='website_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='watchlistitem',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='watchlistitem',
            name='coin_symbol',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='watchlistitem',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='watchlistitem',
            index=models.Index(fields=['coin_symbol', '-added_at'], name='crypto_api__coin_sy_7ef5aa_idx'),
        ),
        migrations.AddIndex(
            model_name='watchlistitem',
            index=models.Index(fields=['is_favorite', '-added_at'], name='crypto_api__is_favo_17a63b_idx'),
        ),
        migrations.AddIndex(
            model_name='watchlistitem',
            index=models.Index(fields=['-last_updated'], name='crypto_api__last_up_77998e_idx'),
        ),
    ]
